# NACE -> ICIO crosswalk
NACE_TO_ICIO = {
    "A": "A01",
    "B": "B07",
    "C10-C12": "C10T12",
    "C13-C15": "C13T15",
    "C16-C18": "C17_18",
    "C16": "C16",
    "C19": "C19",
    "C20": "C20",
    "C20-C21": "C20",
    "C21": "C21",
    "C22-C23": "C22",
    "C24-C25": "C25",
    "C26": "C26",
    "C26-C27": "C26",
    "C27": "C27",
    "C28": "C28",
    "C29-C30": "C29",
    "C31-C33": "C31T33",
    "D": "D",
    "D-E": "D",
    "E": "E",
    "F": "F",
    "G": "G",
    "G45": "G",
    "G46": "G",
    "G47": "G",
    "H": "H49",
    "H49": "H49",
    "H50": "H50",
    "H51": "H51",
    "H52": "H52",
    "H53": "H53",
    "I": "I",
    "J": "J62_63",
    "J58-J60": "J58T60",
    "J61": "J61",
    "J62-J63": "J62_63",
    "K": "K",
    "L": "L",
    "L68A": "L",
    "M": "M",
    "M-N": "M",
    "N": "N",
    "O": "O",
    "O-Q": "O",
    "P": "P",
    "Q": "Q",
    "Q86": "Q",
    "R": "R",
    "R-S": "R",
    "S": "S",
}

SECTOR_LABELS = {
    "A01": "Agriculture",
    "A02": "Forestry",
    "A03": "Fishing",
    "B05": "Coal mining",
    "B06": "Oil & gas",
    "B07": "Metal ores mining",
    "B08": "Other mining",
    "B09": "Mining support",
    "C10T12": "Food & beverages",
    "C13T15": "Textiles & apparel",
    "C16": "Wood products",
    "C17_18": "Paper & printing",
    "C19": "Coke & petroleum",
    "C20": "Chemicals",
    "C21": "Pharmaceuticals",
    "C22": "Rubber & plastics",
    "C23": "Non-metallic minerals",
    "C24A": "Basic metals (ferrous)",
    "C24B": "Basic metals (non-ferrous)",
    "C25": "Fabricated metals",
    "C26": "Electronics & ICT",
    "C27": "Electrical equipment",
    "C28": "Machinery",
    "C29": "Motor vehicles",
    "C301": "Shipbuilding",
    "C302T309": "Other transport equip.",
    "C31T33": "Furniture & repair",
    "D": "Electricity & gas",
    "E": "Water & waste",
    "F": "Construction",
    "G": "Wholesale & retail",
    "H49": "Land transport",
    "H50": "Water transport",
    "H51": "Air transport",
    "H52": "Warehousing",
    "H53": "Postal services",
    "I": "Accommodation & food",
    "J58T60": "Publishing & media",
    "J61": "Telecommunications",
    "J62_63": "IT services",
    "K": "Financial services",
    "L": "Real estate",
    "M": "Professional services",
    "N": "Administrative services",
    "O": "Public admin",
    "P": "Education",
    "Q": "Health & social work",
    "R": "Arts & entertainment",
    "S": "Other services",
    "T": "Household services",
}